### ISSUE TITLE
Incorrect range for Pion/Kaon ME DCA distribution

### ISSUE THREAD

**Issue by MustafaMustafa** [GuannanXie/auau200GeVMixEvents#5]
https://github.com/GuannanXie/auau200GeVMixEvents/blob/master/StPicoMixedEventMaker/StD0Hists.cxx#L79-L80

**Comment by GuannanXie** [comment]
Hello @MustafaMustafa @mlomnitz ,
Yes, this is a bug, i copied this range from TH2Array, and then changed to TH3. Need to fix later.

**Comment by GuannanXie** [comment]
changed the range.
