### ISSUE TITLE
Mass cut range for D0 topological variables

### ISSUE THREAD

**Issue by MustafaMustafa** [GuannanXie/auau200GeVMixEvents#6]
@mlomnitz, @GuannanXie,
Is this repo up to date with the code you used to process the data?

The mass range for D0 selection used here 
https://github.com/GuannanXie/auau200GeVMixEvents/blob/master/StPicoMixedEventMaker/StD0Hists.cxx#L105

is set to 0-2.5
https://github.com/GuannanXie/auau200GeVMixEvents/blob/master/StPicoMixedEventMaker/StMixerCuts.h#L46-L47

Am I missing something?

**Comment by GuannanXie** [comment]
@MustafaMustafa @mlomnitz ,You are right, this is my stupid fault.
And this means we can't get the right topology distribution from data right now.

**Comment by MustafaMustafa** [comment]
Hi @GuannanXie, 

Thanks for checking this. 
It seems you changed it so you can use it in https://github.com/GuannanXie/auau200GeVMixEvents/blob/master/StPicoMixedEventMaker/StPicoEventMixer.cxx#L236

These should be different mass cuts variables.

**Comment by mlomnitz** [comment]
Agreed,
  It is good we found this. I might have a small sample with the correct
mass range if it will help any. Maybe 100M events or so

On Thu, Aug 20, 2015 at 6:24 AM, Mustafa Mustafa notifications@github.com
wrote:

> Hi @GuannanXie https://github.com/GuannanXie,
> 
> Thanks for checking this.
> It seems you changed it so you can use it in
> https://github.com/GuannanXie/auau200GeVMixEvents/blob/master/StPicoMixedEventMaker/StPicoEventMixer.cxx#L236
> 
> These should be different mass cuts variables.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GuannanXie/auau200GeVMixEvents/issues/6#issuecomment-133005788
> .

## 

Michael R. Lomnitz
Ph.D. Candidate in Physics
mlomnitz@kent.edu
309 Smith Hall, Kent OH

**Comment by GuannanXie** [comment]
@MustafaMustafa  Yes, that is the reason why i changed the mass range.
@mlomnitz i remember you have a small bug in the event selection.But maybe it doesn't effect much.

**Comment by GuannanXie** [comment]
Add one more variables for QA Mass range.

**Comment by mlomnitz** [comment]
Hello Guannan and Mustafa,
  I have sent a pull request fixing the range on some of the topological
constants. I believe Mustafa is looking at the other plots in the test file
i produced. Please let me know if there any other issues.
Michael

On Fri, Aug 21, 2015 at 10:51 AM, Guannan Xie notifications@github.com
wrote:

> Add one more variables for QA Mass range.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GuannanXie/auau200GeVMixEvents/issues/6#issuecomment-133511560
> .

## 

Michael R. Lomnitz
Ph.D. Candidate in Physics
mlomnitz@kent.edu
309 Smith Hall, Kent OH

**Comment by GuannanXie** [comment]
already merged, thanks
